# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/tlestang/.pyenv/versions/3.8.1/envs/pybamm/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/tlestang/.pyenv/versions/3.8.1/envs/pybamm/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tlestang/repos/NTD_talk_2021/slides

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tlestang/repos/NTD_talk_2021/slides/output

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/tlestang/.pyenv/versions/3.8.1/envs/pybamm/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/tlestang/.pyenv/versions/3.8.1/envs/pybamm/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tlestang/repos/NTD_talk_2021/slides/output/CMakeFiles /home/tlestang/repos/NTD_talk_2021/slides/output//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tlestang/repos/NTD_talk_2021/slides/output/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named longfunction

# Build rule for target.
longfunction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 longfunction
.PHONY : longfunction

# fast build rule for target.
longfunction/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/longfunction.dir/build.make CMakeFiles/longfunction.dir/build
.PHONY : longfunction/fast

#=============================================================================
# Target rules for targets named longparam

# Build rule for target.
longparam: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 longparam
.PHONY : longparam

# fast build rule for target.
longparam/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/longparam.dir/build.make CMakeFiles/longparam.dir/build
.PHONY : longparam/fast

#=============================================================================
# Target rules for targets named example1

# Build rule for target.
example1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example1
.PHONY : example1

# fast build rule for target.
example1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example1.dir/build.make CMakeFiles/example1.dir/build
.PHONY : example1/fast

#=============================================================================
# Target rules for targets named intro_and_conclusion

# Build rule for target.
intro_and_conclusion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intro_and_conclusion
.PHONY : intro_and_conclusion

# fast build rule for target.
intro_and_conclusion/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intro_and_conclusion.dir/build.make CMakeFiles/intro_and_conclusion.dir/build
.PHONY : intro_and_conclusion/fast

#=============================================================================
# Target rules for targets named nested

# Build rule for target.
nested: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nested
.PHONY : nested

# fast build rule for target.
nested/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nested.dir/build.make CMakeFiles/nested.dir/build
.PHONY : nested/fast

#=============================================================================
# Target rules for targets named slides

# Build rule for target.
slides: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 slides
.PHONY : slides

# fast build rule for target.
slides/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slides.dir/build.make CMakeFiles/slides.dir/build
.PHONY : slides/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... example1"
	@echo "... intro_and_conclusion"
	@echo "... longfunction"
	@echo "... longparam"
	@echo "... nested"
	@echo "... slides"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

